djangor/urls.py
from django.contrib import admin
from django.urls import path
from catalog import views
from seo.views import robots_txt_view
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path  # For django versions from 2.0 and up




urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', views.index, name='index'),
    path('categories/', views.all_cats, name='all_cats'),
    path('category/<slug:slug>/', views.AgencyListView.as_view(), name='catalog'),
    path('company/<slug:slug>/', views.CompanyView.as_view(), name='company'),
    path('robots.txt', robots_txt_view,)

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from slugify import slugify


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, blank=True, unique=True)
    description = models.CharField(max_length=255, blank=True)
    text = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"


class Agency(models.Model):
    name = models.CharField(max_length=255)
    # new
    logo = models.ImageField(upload_to='logos', blank=True)
    website = models.URLField(blank=True)
    slug = models.CharField(max_length=255, unique=True)
    origin_image = models.URLField(blank=True)
    cats = models.ManyToManyField(Category)
    #new have no parser func
    short_description = models.TextField(blank=True)
    description = models.TextField(blank=True)
    rates = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    year = models.IntegerField(blank=True)
    employees = models.CharField(max_length=255, blank=True)
    services = models.TextField(blank=True)
    scores = models.CharField(max_length=255, default='5')
    email = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=255, blank=True)
    address = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Agencies"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Review(models.Model):
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=255)
    summary = models.CharField(max_length=255, blank=True)
    review = models.TextField(blank=True)
    score = models.TextField(max_length=255, default='5', blank=True)

    def __str__(self):
        return self.name

seo/models.py
from django.db import models

# Create your models here.

class RobotsTxt(models.Model):
    text = models.TextField()

    def __str__(self):
        return 'robots.txt'

    def save(self, *args, **kwargs):
        self.pk = 1
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'robots.txt'
        verbose_name_plural = 'robots.txt'

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponseBadRequest
from django.http import HttpResponse
from .models import Category, Agency
from django.db.models import Count
from django.views.generic import TemplateView, DeleteView, ListView


def index(request):

    category = Category.objects.get(slug='mobile-app-development')
    companies = category.agency_set.all()[:12]

    context = {
        'companies': companies,
    }
    response = render(request, 'index.html', context)

    return response


def all_cats(request):
    all_cats = Category.objects.annotate(
        agency_count=Count('agency')).order_by('-agency_count')

    context = {
        'all_cats': all_cats
    }
    response = render(request, 'categories.html', context)
    return response

class CatalogView(DeleteView):
    model = Category
    template_name = 'catalog.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rates_list = context['object'].agency_set.all().values('rates').distinct()
        employees_num = context['object'].agency_set.all().values('employees').distinct()
        companies = context['object'].agency_set.all()[:30]
        context['rates_list'] = rates_list
        context['employees_num'] = employees_num
        context['companies'] = companies

        return context


class AgencyListView(ListView):
    model = Agency
    template_name = 'catalog.html'
    paginate_by = 30

    def get_queryset(self):
        cat_slug = self.kwargs.get('slug')
        category = Category.objects.get(slug=cat_slug)
        self.category = category
        employees = self.request.GET.get('employees', None)
        rates = self.request.GET.get('rate', None)
        if employees:
            companies = Agency.objects.filter(cats__in=[category], employees=employees)
            # companies = category.agency_set.filter(employees=employees)[:30]
        elif rates:
            companies = Agency.objects.filter(cats__in=[category], rates=rates)
            # companies = category.agency_set.filter(rates=rates)[:30]
        else:
            # companies = category.agency_set.all()[:30]
            companies = Agency.objects.filter(cats__in=[category])
        return companies


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        rates_list = self.category.agency_set.all().values('rates').distinct()
        employees_num = self.category.agency_set.all().values('employees').distinct()
        context['rates_list'] = rates_list
        context['employees_num'] = employees_num
        return context


# def catalog(request, **kwargs):
#     slug = kwargs.get('slug', None)
#     if not slug:
#         return HttpResponseBadRequest()
#
#     category = Category.objects.get(slug=slug)
#
#     employees = request.GET.get('employees', None)
#     rates = request.GET.get('rate', None)
#
#     if employees:
#         companies = category.agency_set.filter(employees=employees)[:30]
#     elif rates:
#         companies = category.agency_set.filter(rates=rates)[:30]
#     else:
#         companies = category.agency_set.all()[:30]
#
#     rates_list = category.agency_set.all().values('rates').distinct()
#     employees_num = category.agency_set.all().values('employees').distinct()
#
#     context = {
#         'companies': companies,
#         'main_cat': category,
#         'employees_num': employees_num,
#         'rates_list': rates_list,
#     }
#
#     response = render(request, 'catalog.html', context)
#     return response


#переписал с функции на класс - тоже что и снизу, только вью пришлось править
class CompanyView(DeleteView):
    model = Agency
    context_object_name = 'agency'  #по дефолту во вьюшку отправляет с названием object
    template_name = 'company-single.html'

# def company(request, **kwargs):
#
#     slug = kwargs.get('slug', None)
#
#     if not slug:
#         return HttpResponseBadRequest()
#
#     company = Agency.objects.get(slug=slug)
#
#     context = {
#         'company': company.name,
#         'logo': company.logo,
#         'description': company.description,
#         'rates': company.rates,
#         'location': company.location,
#         'year': company.year,
#         'employees': company.employees,
#         'services': company.services,
#         'scores': company.scores,
#         'email': company.email,
#         'phone': company.phone,
#         'address': company.address,
#         'company_cats': company.cats.all()
#     }
#
#
#     response = render(request, 'company-single.html', context)
#     return response

seo/views.py
from django.shortcuts import render
from .models import RobotsTxt

def robots_txt_view(reqest):
    robots = RobotsTxt.objects.get()
    context = {'robots': robots}
    response = render(reqest, 'robots.txt', context, content_type='text/plain')
    return response

templates/catalog.html
{% extends 'index.html' %}

{% load static %}
{% block content %}
  <!--/ Intro Single star /-->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">Top {{ category.name }} Companies</h1>
            <span class="color-text-a">Top rated companies</span>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'index' %}">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                {{ category.name }}
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Single End /-->

  <!--/ Property Grid Star /-->
  <section class="property-grid grid">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="grid-option">
            <form>
              <select class="custom-select">
                <option selected>All</option>
                <option value="1">New to Old</option>
                <option value="2">For Rent</option>
                <option value="3">For Sale</option>
              </select>
            </form>
          </div>
        </div>
        <!--item start-->
        {% for company in agency_list %}
    <div class="col-lg-4 col-md-6 mb-4">
    <!--Card-->
    <div class="card card-cascade narrower mb-4" style="margin-top: 28px">

      <!--Card image-->
      <div class="view view-cascade" style="margin-right: auto;">
        <img src="{{company.logo.url}}" class="{{company.name}}"
          alt="" style="width: auto; min-height: 40px">
        <a href="{% url 'company' company.slug %}">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

      <!--/.Card image-->

      <!--Card content-->
      <div class="card-body card-body-cascade">
        <h4 class="pink-text">{{company.name}}</h4>
        <div class="my-rating-4" data-rating="{{ company.scores }}"></div>
        <!--Title-->
        <h5 class="card-title">{{ company.rates}}</h5>
        <!--Text-->
        <p class="card-text">{{ company.location }}</p>

        <a class="btn btn-unique" href="{% url 'company' company.slug %}">View more</a>



      </div>
      <!--/.Card content-->

    </div>
    <!--/.Card-->

  </div>
        {% endfor %}
        <!--item ends-->

      </div>
      {% if is_paginated %}
      <div class="row">
        <div class="col-sm-12">
          <nav class="pagination-a">
            <ul class="pagination justify-content-end">
              {% if page_obj.has_previous %}
              <li class="page-item">
                {% if page_obj.previous_page_number == 1%}
                <a class="page-link" href="/category/{{ category.slug }}/" tabindex="-1">
                {% else %}
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">
                {% endif %}
                  <span class="ion-ios-arrow-back"></span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">
                  <span class="ion-ios-arrow-back"></span>
                </a>
              </li>
              {% endif %}


              {% for page in paginator.page_range %}
              {% if page_obj.number == page %}
              <li class="page-item active">
                {% if page == 1 %}
                <a class="page-link" href="/category/{{ category.slug }}/">{{ page }}</a>
                {% else %}
                <a class="page-link" href="?page={{page}}">{{ page }}</a>
                {% endif %}
              </li>
              {% else %}
              <li class="page-item">
                {% if page == 1 %}
                <a class="page-link" href="/category/{{ category.slug }}/">{{ page }}</a>
                {% else %}
                <a class="page-link" href="?page={{page}}">{{ page }}</a>
                {% endif %}
              </li>
              {% endif %}
              {% endfor %}


              {% if page_obj.has_next %}
              <li class="page-item next">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                  <span class="ion-ios-arrow-forward"></span>
                </a>
              </li>
              {% else %}
              <li class="page-item next disabled">
                <a class="page-link" href="#">
                  <span class="ion-ios-arrow-forward"></span>
                </a>
              </li>
              {% endif %}

            </ul>
          </nav>
        </div>
      </div>
    </div>
    {% endif %}
  </section>
<section>
<div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">By employees</h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  {% for empl in employees_num %}
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="?employees={{empl.employees}}">{{ empl.employees }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">Rates</h3>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                {% for rate in rates_list %}
                {%if rate.rates|length > 1%}
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="?rate={{ rate.rates }}">{{ rate.rates }}</a>
                </li>
                {% endif %}
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    </section>
  <!--/ Property Grid End /-->

{% endblock %}

templates/categories.html
{% extends 'index.html' %}

{% load static %}
{% block content %}
<div class="row section-property section-t8">
        <div class="container col-sm-12 col-md-8 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h1 class="w-title-a text-brand">All Services</h1>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                {% for cater in all_cats %}
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="{% url 'catalog' cater.slug %}"> {{cater.name}}</a>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
</div>
{% endblock %}

templates/company-single.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
  <!--/ Intro Single star /-->
  <section class="intro-single">
    <div class="container">
      <div class="row">

        <div class="col-md-12 col-lg-8">

          <div class="title-single-box">

            <h1 class="title-single">{{ agency.name }}</h1>
            <span class="color-text-a">Founded {{ agency.year }}</span>
          </div>

        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'index' %}">Home</a>
              </li>
              <li class="breadcrumb-item">
                <a href="{% url 'all_cats' %}">Categories</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                {{ agency.name }}
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Single End /-->

  <!--/ Property Single Star /-->
  <section class="property-single nav-arrow-b">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <div class="row justify-content-between">
            <div class="col-md-5 col-lg-4">
              <div class="property-price d-flex foo">
                <div class="card-header-c d-flex">
                  <div class="card-box-ico" style="min-width: 100px; padding: 1rem;">
                    <img src="{{ agency.logo.url }}" itemprop="image" alt="{{ agency.name }}" style="height: auto; object-fit: contain; width: 100%">
                  </div>
                </div>
              </div>
              <div class="property-summary">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="title-box-d section-t4">
                      <h3 class="title-d">Quick Summary</h3>
                    </div>
                  </div>
                </div>
                <div class="summary-list">

                  <ul class="list">
                    <li class="d-flex justify-content-between">
                      <strong>Rating: </strong>
                      <div class="my-rating-4" data-rating="{{ agency.scores }}"></div>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Rates:</strong>
                      <span>{{ agency.rates }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Location:</strong>
                      <span>{{ agency.location }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Year:</strong>
                      <span>{{ agency.year }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Employees:</strong>
                      <span>{{ agency.employees }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Phone:</strong>
                      <span>{{ agency.phone }}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-md-7 col-lg-7 section-md-t3">
              <div class="row">
                <div class="col-sm-12">
                  <div class="title-box-d">
                    <h3 class="title-d">Description</h3>
                  </div>
                </div>
              </div>
              <div class="property-description">
                <p class="description color-text-a">
                  {{ agency.description }}
                </p>
              </div>
              <div class="row section-t3">
                <div class="col-sm-12">
                  <div class="title-box-d">
                    <h3 class="title-d">Servises</h3>
                  </div>
                </div>
              </div>
              <div class="amenities-list color-text-a">
                <ul class="list-a no-margin">
                  {% for cat in agency.cats.all %}
                    <li><a href="{% url 'catalog' cat.slug %}">{{ cat.name }}</a></li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-10 offset-md-1">
          <ul class="nav nav-pills-a nav-pills mb-3 section-t3" id="pills-tab" role="tablist">

            <li class="nav-item">
              <a class="nav-link active" id="pills-map-tab" data-toggle="pill" href="#pills-map" role="tab" aria-controls="pills-map"
                aria-selected="false">Location</a>
            </li>
          </ul>
          <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-map" role="tabpanel" aria-labelledby="pills-map-tab">
                <strong>Address:</strong>
                <p><span>{{ agency.address }}</span></p>
              <iframe src="https://maps.google.com/maps?q={{agency.address}}&t=&z=13&ie=UTF8&iwloc=&output=embed"
                width="100%" height="460" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="row section-t3">
            <div class="col-sm-12">
              <div class="title-box-d">
                <h3 class="title-d">Contact Agent</h3>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-lg-4">
              <img src="{% static 'img/agent-4.jpg' %}" alt="" class="img-fluid">
            </div>
            <div class="col-md-6 col-lg-4">
              <div class="property-agent">
                <h4 class="title-agent">Anabella Geller</h4>
                <p class="color-text-a">
                  Nulla porttitor accumsan tincidunt. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet
                  dui. Quisque velit nisi,
                  pretium ut lacinia in, elementum id enim.
                </p>
                <ul class="list-unstyled">
                  <li class="d-flex justify-content-between">
                    <strong>Phone:</strong>
                    <span class="color-text-a">(222) 4568932</span>
                  </li>
                  <li class="d-flex justify-content-between">
                    <strong>Mobile:</strong>
                    <span class="color-text-a">777 287 378 737</span>
                  </li>
                  <li class="d-flex justify-content-between">
                    <strong>Email:</strong>
                    <span class="color-text-a">annabella@example.com</span>
                  </li>
                  <li class="d-flex justify-content-between">
                    <strong>Skype:</strong>
                    <span class="color-text-a">Annabela.ge</span>
                  </li>
                </ul>
                <div class="socials-a">
                  <ul class="list-inline">
                    <li class="list-inline-item">
                      <a href="#">
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#">
                        <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#">
                        <i class="fa fa-dribbble" aria-hidden="true"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-md-12 col-lg-4">
              <div class="property-contact">
                <form class="form-a">
                  <div class="row">
                    <div class="col-md-12 mb-1">
                      <div class="form-group">
                        <input type="text" class="form-control form-control-lg form-control-a" id="inputName"
                          placeholder="Name *" required>
                      </div>
                    </div>
                    <div class="col-md-12 mb-1">
                      <div class="form-group">
                        <input type="email" class="form-control form-control-lg form-control-a" id="inputEmail1"
                          placeholder="Email *" required>
                      </div>
                    </div>
                    <div class="col-md-12 mb-1">
                      <div class="form-group">
                        <textarea id="textMessage" class="form-control" placeholder="Comment *" name="message" cols="45"
                          rows="8" required></textarea>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <button type="submit" class="btn btn-a">Send Message</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--/ Property Single End /-->
{% endblock %}

templates/footer.html
 <!--/ footer Star /-->
  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">IT Companies Catalog</h3>
            </div>
            <div class="w-body-a">
              <p class="w-text-a color-text-a">
                Enim minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat duis
                sed aute irure.
              </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> contact@gmail.com</li>
                <li class="color-a">
                  <span class="color-text-a">Email .</span> +54 356 945234</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">The Company</h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Site Map</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Legal</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Agent Admin</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Careers</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Affiliate</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Privacy Policy</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">International sites</h3>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="#">Venezuela</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="#">China</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="#">Hong Kong</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="#">Argentina</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="#">Singapore</a>
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> <a href="#">Philippines</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">Home</a>
              </li>
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Property</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Blog</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-dribbble" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-footer">
            <p class="copyright color-text-a">
              &copy; Copyright
              <span class="color-a">Top IT Companies</span> All Rights Reserved.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--/ Footer End /-->